import GNB from '@/components/commons/GNB';
import ModalContainer from '@/components/commons/ModalContainer';
import { ModalStoreProvider } from '@/providers/ModalProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ModalStoreProvider>
					<ModalContainer />
					{/* TODO: 공통 디자인 뽑기 */}
					<div className="box-border min-h-screen bg-gray-100" style={{ fontFamily: 'var(--font-pretendard)' }}>
						<GNB />
						{children}
					</div>
				</ModalStoreProvider>
			</body>
		</html>
	);
}
